### ISSUE TITLE
java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by fkonietzny** [Abastro/StellarSky#36]
Hi, with v0.1.21 and v0.1.22 I get the following exception:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_72]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_72]
        at stellarium.stellars.Earth.getEcRPos(Earth.java:15) ~[Earth.class:?]
        at stellarium.stellars.Earth.update(Earth.java:21) ~[Earth.class:?]
        at stellarium.stellars.StellarManager.update(StellarManager.java:303) ~[StellarManager.class:?]
        at stellarium.StellarTickHandler.tickStart(StellarTickHandler.java:72) ~[StellarTickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_298_StellarTickHandler_tickStart_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

forge-1.7.10-10.13.4.1614

**Comment by Abastro** [comment]
I'll fix it immediately!
